// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow(arg1) {
  return window['go']['src']['App']['CloseWindow'](arg1);
}

export function Greet(arg1) {
  return window['go']['src']['App']['Greet'](arg1);
}
